Traceback (most recent call last):
  File "C:\Users\rimsha\turingenv\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\rimsha\turingenv\lib\site-packages\nbclient\client.py", line 1085, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\rimsha\turingenv\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\rimsha\turingenv\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\rimsha\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\rimsha\turingenv\lib\site-packages\nbclient\client.py", line 551, in async_execute
    await self.async_execute_cell(
  File "C:\Users\rimsha\turingenv\lib\site-packages\nbclient\client.py", line 846, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\rimsha\turingenv\lib\site-packages\nbclient\client.py", line 748, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import ipywidgets as widgets
container2 = widgets.HBox([origin, textbox])
widgets.VBox([container,
              container2,
              g])
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Input [1;32mIn [16][0m, in [0;36m<module>[1;34m[0m
[0;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mipywidgets[39;00m [38;5;28;01mas[39;00m [38;5;21;01mwidgets[39;00m
[1;32m----> 2[0m container2 [38;5;241m=[39m widgets[38;5;241m.[39mHBox([[43morigin[49m, textbox])
[0;32m      3[0m widgets[38;5;241m.[39mVBox([container,
[0;32m      4[0m               container2,
[0;32m      5[0m               g])

[1;31mNameError[0m: name 'origin' is not defined
NameError: name 'origin' is not defined

